### ISSUE TITLE
Validierung Student-Emailadresse

### ISSUE THREAD

**Issue by graphics80** [marcel-suter-bzz/exam_frontend#5]
Da Volkan es schafft die Mailadressen der Lernenden falsch in die Liste einzutragen wäre eine Validierung gegenüber des Sharepoints/AD notwendig...

Vllt ist das ja auch schon drin...

**Comment by marcel-suter-bzz** [comment]
Die Eingabe von Lernender/Lehrperson erfolgt über eine Datalist. Diese wird mit den Daten aus AD befüllt.
Es müsste jemand schon mit Gewalt einen falschen Eintrag fabrizieren.

**Comment by graphics80** [comment]
Yeah, so einfach kann ein Issue resolved werden. Resolves #5
